### ISSUE TITLE
Zoom Video conferencing screen sharing dark overlay

### ISSUE THREAD

**Issue by UtahDave** [regolith-linux/regolith-compton-config#2]
I'm running the current latest release of Regolith.

When using the Zoom Videoconferencing software and trying to share my desktop I get a dark overlay that mostly obscures the content I'm trying to share.

I found the following suggestion that worked for me:

https://www.reddit.com/r/i3wm/comments/apvq2x/zoomus_screen_sharing_black_screen_occasionally/elwglhj/

Specifically in `/etc/regolith/compton/config` I added `"name = 'cpt_frame_window'"` to the `shadow-exclude` config option.  This worked and I have seen any other adverse reactions to this change.

Opening a PR shortly with this addition.

**Comment by kgilmer** [comment]
Thanks for all the details in the ticket @UtahDave !
